# Generated by Django 2.2.18 on 2025-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='uploads/', verbose_name='封面图片'),
        ),
    ]
