# Generated by Django 2.2.18 on 2025-07-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250703_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='picture',
        ),
    ]
