# Generated by Django 5.2.4 on 2025-07-05 08:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_article_id_alter_category_id_alter_comment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
